### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by wanboyang** [cvpr-anon/captioning#3]
Thank you for open-source code,
Can I use the pretrained models, which are provided in link"https://drive.google.com/drive/folders/1kPoRVsUuj57Scon-SbUJXNl555ee6sjo"  to generate caption for new data?

**Comment by fawazsammani** [comment]
Hi. Thanks for your interest in our work. Our method does not generate data, but rather modifies data. You can try to give it a caption as input, and if it thinks there is something wrong with it, it will correct it, and otherwise it will leave it unchanged. Modifying the data essentially means generating "similar" data if you'd like to look at it in a very abstract and general way. So you can try inputting a caption and getting a similar caption as output.

**Comment by fawazsammani** [comment]
Feel free to open this issue if you have any other questions.

**Comment by zxh19976666** [comment]
Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!
